### PR TITLE
Add form validation to authentication page

### PR DESCRIPTION
**Pull request by Daviancold**
Refactored validation logic to utilise the same logic as the one used in Account Page. Consolidated all form values into a single object for easier subsequent processing as well.

Completes #71

### CODE REVIEW

**Comment by shishirbychapur** [comment]
the password reset would also require fields to reset and confirm the reset password (it can be done later though)

**Comment by Daviancold** [comment]
> the password reset would also require fields to reset and confirm the reset password (it can be done later though)

Are you referring to the "forgot my password" link?

**Comment by shishirbychapur** [comment]
yeah correct

**Comment by shishirbychapur** [comment]
btw i got some time on my hands, if there's any stuff left to do, you can lmk!

**Comment by Daviancold** [comment]
> btw i got some time on my hands, if there's any stuff left to do, you can lmk!

Could you help me to finish this? As well as help fix my CI issues haha 😬

**Comment by shishirbychapur** [comment]
okay sure 👍

**Comment by shishirbychapur** [comment]
Done @Daviancold (Now all authentication forms have validation)

**Comment by Daviancold** [comment]
> Done @Daviancold (Now all authentication forms have validation)

Hi, could you revert the changes to the naming of the form input, specifically the one where you changed password to Login Password? I am using it for the account password reset also and used the word password to avoid confusion

**Pull request merged**
