### PR TITLE
Add GET API for Retrieving User Profile

### PR DESCRIPTION
**Pull request by Daviancold**
Completes #9 

Any comments are appreciated!

### CODE REVIEW

**Review by glemenneo — APPROVED** [review]
Lgtm

**Comment by shishirbychapur** [comment]
nit: similar to my pr's comments, lets send 500 status code if the user is not found?

**Comment by glemenneo** [comment]
> nit: similar to my pr's comments, lets send 500 status code if the user is not found?

Why send 500 if the user not found? 500 should be for server errors

**Comment by shishirbychapur** [comment]
okay, but didnt you implement some mechanism to auto catch errors, so we need to do an extra check and send 404? (correct me if im wrong)

**Comment by Daviancold** [comment]
> okay, but didnt you implement some mechanism to auto catch errors, so do we need to do an extra check and send 404? (correct me if im wrong)

On this point, the database doesn't return 404 when the id is not found, rather it returns an empty object {}, so i opted to return an error 404 to help with debugging if needed

**Comment by shishirbychapur** [comment]
okay that makes sense then, LGTM

**Comment by glemenneo** [comment]
> okay, but didnt you implement some mechanism to auto catch errors, so do we need to do an extra check and send 404? (correct me if im wrong)

Yes but it seems the behaviour of mongoose is inconsistent. My error catcher only handles explicit mongoose.Error errors, all other errors are defaulted to 500

**Comment by glemenneo** [comment]
> > okay, but didnt you implement some mechanism to auto catch errors, so do we need to do an extra check and send 404? (correct me if im wrong)
> 
> On this point, the database doesn't return 404 when the id is not found, rather it returns an empty object {}, so i opted to return an error 404 to help with debugging if needed

This is expected behaviour from the findbyid function, the return type is Promise<IUser | null> so we have to do explicit checking

**Pull request merged**
