### PR TITLE
Implement Waiting Queue

### PR DESCRIPTION
**Pull request by Daviancold**
Satisfies #93

### CODE REVIEW

**Review by shishirbychapur — APPROVED** [review]
LGTM. tested on my side.

One question though. Suppose a user with the following params queues: `ADVANCED.EASY.ARRAYS`

Then, is the expected behavior supposed to be to create more than 1 queues (if they dont alr exist), one for each proficiency? Or is to supposed to just check if the queues exist? I ask this because the `INTERMEDIATE.EASY.ARRAYS` and `EXPERT.EASY.ARRAYS` queues got created as well.

Also, the profile page has only three proficiency levels, but in ur logic there are 4, so can we standardize that as well...

**Comment by glemenneo** [comment]
> LGTM. tested on my side.
> 
> One question though. Suppose a user with the following params queues: `ADVANCED.EASY.ARRAYS`
> 
> Then, is the expected behavior supposed to be to create more than 1 queues (if they dont alr exist), one for each proficiency? Or is to supposed to just check if the queues exist? I ask this because the `INTERMEDIATE.EASY.ARRAYS` and `EXPERT.EASY.ARRAYS` queues got created as well.
> 
> Also, the profile page has only three proficiency levels, but in ur logic there are 4, so can we standardize that as well...

the shared enum of proficiency has 4 levels, if we standardise to 3 then we can remove it from the enum and simplify the queue matching logic as well. I've checked the origin milestone 1 doc and theres also only 3 levels, so shud be good to remove the EXPERT level

**Comment by Daviancold** [comment]
> LGTM. tested on my side.
> 
> One question though. Suppose a user with the following params queues: `ADVANCED.EASY.ARRAYS`
> 
> Then, is the expected behavior supposed to be to create more than 1 queues (if they dont alr exist), one for each proficiency? Or is to supposed to just check if the queues exist? I ask this because the `INTERMEDIATE.EASY.ARRAYS` and `EXPERT.EASY.ARRAYS` queues got created as well.
> 
> Also, the profile page has only three proficiency levels, but in ur logic there are 4, so can we standardize that as well...

The behaviour of the queue is such that it is only deleted if the consumer disconnects from the queue. However, in our implementation, we do not use a consumer as we need to be flexible with how we check our messages, hence we are unable to use auto-delete.

With the latest pushed changes, the queue will be deleted if it is empty while checking the queue for match, and if the queue becomes empty after a match.

**Comment by shishirbychapur** [comment]
works on my side 👍 lgtm

**Pull request merged**
