### PR TITLE
Feat login

### PR DESCRIPTION
**Pull request by lynnlow175**

### CODE REVIEW

**Comment by yunruu** [comment]
There is a failed SSR hydration in this branch 
image

**Comment by Daviancold** [comment]
image

There is some margin here in the root div, i think it should be removed to match the figma, otherwise looks good to me!

**Comment by Daviancold** [comment]
image

Additionally the toast box is at the bottom, perhaps @yunruu @shishirbychapur ya'll can take a look at this too

**Comment by lynnlow175** [comment]
> image
> 
> Additionally the toast box is at the bottom, perhaps @yunruu @shishirbychapur ya'll can take a look at this too

whats wrong?

**Comment by shishirbychapur** [comment]
the toast can be fixed later imo, currently the page isn't functional yet, and the error message is generic. for now, i think it's fine

**Review by shishirbychapur — APPROVED** [review]
LGTM

**Pull request merged**
